title:              Blog
tagline:            on Powering FinTech with Data Science
description:        Powering FinTech with Data Science.
url:                http://young-xli.github.io

author:
  name:             Young Li
  url:              http://young-xli.github.io
  email:            xli528@bloomberg.net

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post

theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
  
